config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pets
  resources :posts do
    resources :comments, only: :create
  end
  resources :users, only: :show
  root to: "pets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :comment_text, presence: true
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '男の子' },
    { id: 3, name: '女の子' },
    { id: 4, name: '指定なし' }
  ]
  include ActiveHash::Associations
  has_many :pets
end

app/models/pet.rb
class Pet < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  has_one_attached :image
  belongs_to :gender

  with_options presence: true do
    validates :name
    validates :information
    validates :pet_kind
    validates :gender_id, numericality: { other_than: 1 }
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments

  with_options presence: true do
    validates :post_title
    validates :post_text
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pets
  has_many :posts
  has_many :comments

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates :password, format: { with: PASSWORD_REGEX }
  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/posts/#{comment.post.id}"  # コメントと結びつくツイートの詳細画面に遷移する
  end

  private

  def comment_params
    params.require(:comment).permit(:comment_text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  before_action :redirect, only: [:destroy, :edit]

  def index
    @pets = Pet.includes(:user).all.order('created_at DESC')
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
    if @pet.user_id == current_user.id
    else
      redirect_to root_path
    end
  end

  def update
    @pet.update(pet_params)
    if @pet.valid?
      redirect_to pets_path(pet_params)
    else
      render 'edit'
    end
  end

  def destroy
    @pet.destroy
    redirect_to root_path
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def redirect
    redirect_to action: :index if current_user.id != @pet.user.id
  end

  def pet_params
    params.require(:pet).permit(:name, :information, :gender_id, :pet_kind, :image).merge(user_id: current_user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :redirect, only: [:destroy, :edit]

  def index
    @posts = Post.includes(:user).all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    if @post.user_id == current_user.id
    else
      redirect_to post_path
    end
  end

  def update
    @post.update(post_params)
    if @post.valid?
      redirect_to post_path(post_params)
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def redirect
    redirect_to action: :index if current_user.id != @post.user.id
  end

  def post_params
    params.require(:post).permit(:post_title, :post_text, :image).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @pets = user.pets
    @posts = user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hachuha</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/edit.html.erb
<%= render "shared/header" %>

<div class="pets-reg-main">
    <h2 class="pets-reg-title">商品の情報を入力</h2>
<%= form_with model: @pet, local: true do |f| %>
     <%= render 'shared/error_messages', model: f.object %>

<div class="img-upload">
      <div class="weight-bold-text">
        ペットの写真
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
           <div id="previews"></div> 
             <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"pet-image" %>
      </div>
</div>
 
 <div class="new-pets">
      <div class="weight-bold-text">
        ペットのニックネーム
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"pets-text", id:"pet-name", placeholder:"例）ジェマ（必須 40文字まで)", maxlength:"40" %>
      <div class="weight-bold-text">
        ペットの書類
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :pet_kind, class:"pets-text", id:"pet-name", placeholder:"例）わんちゃん（必須 40文字まで)", maxlength:"40" %>
     性別
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class:"select-box", id:"pet-gender"}) %>
       
      <div class="pets-explain">
        <div class="weight-bold-text">
          ペットについての情報
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :information, class:"pets-text", id:"pet-info", placeholder:"性格、特徴、好きなものなど。例）ジェマは白黒の3歳のワンちゃんです。近くの公園の散歩と餌が好きです！他の犬と遊ぶのが大好きです。" ,rows:"7" ,maxlength:"1000" %>
        <div class="reg-btn-contents">
      
      
      <%= f.submit "変更する" ,class:"reg-btn" %>
      <%=link_to 'もどる', pet_path(@pet), method: :get, class:"back-btn" %>

</div></div>
    
    </div>


 

 
<% end %>
<%= render "shared/footer" %>

app/views/pets/index.html.erb
<%= render "shared/header" %>

<div class="explain">
 <%= link_to image_tag("cat.jpg", class:"dog-image") %>
<ul class="explain-texts">
<li class="explain-text">1.  登録して、飼っているペットの情報を記入！</li>
<li class="explain-text">2.  可愛いペットの写真、約立つ情報を交換できる！</li>
<li class="explain-text">3.  もちろん、他の飼い主とペットと一緒に散歩へ行きましょう！</li>
</ul>
</div>
<div class="wrap-head">
<h2 class="heading-name">登録されているペット</h2>
</div>



<div class='pet-contents'>
<ul class='pet-lists'>
      <% @pets.each do |pet| %>
      <li class='list'>
        <%= link_to pet_path(pet.id) do %>
        <div class='pet-img-content'>
          <%= image_tag pet.image, class: "pet-img"%>
     </div>
        <div class='pet-info'>
          <h3 class='pet-name'>
            <%= pet.pet_kind %>:<%= pet.name %>
          </h3>
        </div>
        <% end %>
         </li>
    <% end %>
 </ul>
</div>

<%= render "shared/footer" %>

app/views/pets/new.html.erb
<%= render "shared/header" %>

<div class="pets-reg-main">
    <h2 class="pets-reg-title">商品の情報を入力</h2>
<%= form_with model: @pet, url:pets_path, local: true do |f| %>
     <%= render 'shared/error_messages', model: f.object %>

<div class="img-upload">
      <div class="weight-bold-text">
        ペットの写真
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
           <div id="previews"></div> 
             <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"pet-image" %>
      </div>
</div>
 
 <div class="new-pets">
      <div class="weight-bold-text">
        ペットのニックネーム
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"pets-text", id:"pet-name", placeholder:"例）ジェマ（必須 40文字まで)", maxlength:"40" %>
      <div class="weight-bold-text">
        ペットの書類
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :pet_kind, class:"pets-text", id:"pet-name", placeholder:"例）わんちゃん（必須 40文字まで)", maxlength:"40" %>
     性別
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class:"select-box", id:"pet-gender"}) %>
       
      <div class="pets-explain">
        <div class="weight-bold-text">
          ペットについての情報
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :information, class:"pets-text", id:"pet-info", placeholder:"性格、特徴、好きなものなど。例）ジェマは白黒の3歳のワンちゃんです。近くの公園の散歩と餌が好きです！他の犬と遊ぶのが大好きです。" ,rows:"7" ,maxlength:"1000" %>
        <div class="reg-btn-contents">
      
      
      <%= f.submit "登録する" ,class:"reg-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
</div></div>
    
    </div>


 

 
<% end %>
<%= render "shared/footer" %>

app/views/pets/show.html.erb
<%= render "shared/header" %>

<div class="pet-show">
  <div class="pet-box">
    <h2 class="name">
      <a class= "user-pet" href="/users/<%= @pet.user.id %>"><%= @pet.user.nickname %>    </a>さんの
<%= @pet.name %>
    </h2>
    <div class="pet-img-content">
      <%= image_tag @pet.image ,class:"pet-box-img" %>
    </div>
      <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-pet">ペットの性別</th>
          <td class="detail-value"><%= @pet.gender.name %></td>
        </tr><th class="detail-pet">ペットの書類</th>
          <td class="detail-value"><%= @pet.pet_kind %></td>
        </tr>
          
      </tbody>
 </table>
 <div class="pet-explain-box">
      <span><%= @pet.information %></span>
    </div>
<% if user_signed_in? %> 
    <% if current_user.id == @pet.user_id %>
    <%= link_to "情報の編集", edit_pet_path(@pet), method: :get, class: "pet-red-btn" %>
    <p class="or-text">or</p>
    <%= link_to "削除", pet_path(@pet), method: :delete, class:"pet-destroy" %>
    <% else user_signed_in? && current_user.id  != @pet.user_id %>
    <%= link_to "いいね", "#" ,class:"pet-red-btn"%>
<% end %>
<% end %>
    
</div>
    </form>
  </div>

<%= render "shared/footer" %>

app/views/posts/edit.html.erb
<%= render "shared/header" %>

<div class="pets-reg-main">
    <h2 class="pets-reg-title">ポスト入力</h2>
<%= form_with model: @post, local: true do |f| %>
     <%= render 'shared/error_messages', model: f.object %>

<div class="img-upload">
      <div class="weight-bold-text">
        画像
        <span class="indispensable">任意</span>
      </div>
      <div class="click-upload">
           <div id="previews"></div> 
             <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"pet-image" %>
      </div>
</div>
 
 <div class="new-pets">
      <div class="weight-bold-text">
        タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :post_title, class:"pets-text", id:"pet-name", placeholder:"例）秋に散歩する一番いい公園　ー　５", maxlength:"40" %>
      <div class="pets-explain">
        <div class="weight-bold-text">
          テキスト
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :post_text, class:"post-text", id:"pet-info", placeholder:"例）秋の始まりです！ワンちゃんと散歩する際に。。。" %>
        <div class="reg-btn-contents">
      
      
      <%= f.submit "更新する" ,class:"reg-btn" %>
      <%=link_to 'もどる', posts_path, class:"back-btn" %>
</div>
    </div>
   </div>
   </div>
<% end %>


<%= render "shared/footer" %>

app/views/posts/index.html.erb
<%= render "shared/header" %>

<div class="contents row">
  <% @posts.each do |post| %>
    <div class="content_post" > 
   
    <span class="post-title">
        <%= post.post_title %>
           
      </span> <br>     by <a class= "user-pet" href="/users/<%= post.user.id %>"><%= post.user.nickname %>    </a>
      <p class="post-texts"><%= post.post_text %></p>
           <%= link_to "詳細", post_path(post.id) %>
    </div> 
    
  <% end %>
</div>

<%= render "shared/footer" %>

app/views/posts/new.html.erb
<%= render "shared/header" %>

<div class="pets-reg-main">
    <h2 class="pets-reg-title">ポスト入力</h2>
<%= form_with model: @post, url:posts_path, local: true do |f| %>
     <%= render 'shared/error_messages', model: f.object %>

<div class="img-upload">
      <div class="weight-bold-text">
        画像
        <span class="indispensable">任意</span>
      </div>
      <div class="click-upload">
           <div id="previews"></div> 
             <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"pet-image" %>
      </div>
</div>
 
 <div class="new-pets">
      <div class="weight-bold-text">
        タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :post_title, class:"pets-text", id:"pet-name", placeholder:"例）秋に散歩する一番いい公園　ー　５", maxlength:"40" %>
      <div class="pets-explain">
        <div class="weight-bold-text">
          テキスト
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :post_text, class:"post-text", id:"pet-info", placeholder:"例）秋の始まりです！ワンちゃんと散歩する際に。。。" %>
        <div class="reg-btn-contents">
      
      
      <%= f.submit "登録する" ,class:"reg-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
</div>
    </div>
   </div>
   </div>
<% end %>


<%= render "shared/footer" %>

app/views/posts/show.html.erb
<%= render "shared/header" %>

<div class="contents row">
    <div class="content_post" > 
    <span class="post-title">
        <%= @post.post_title %>
        <br>    by <a class= "user-pet" href="/users/<%= @post.user.id %>"><%= @post.user.nickname %>    </a>
           
      </span>
      <p class="post-texts"><%= @post.post_text %></p>  
               <div> <%= image_tag @post.image, class: "message-image" if @post.image.attached? %> </div>

     <% if user_signed_in? %> 
    <% if current_user.id == @post.user_id %>
<div class="buttons">
    <%= link_to "編集", edit_post_path(@post), method: :get, class: "post-edit" %>
    <p class="or-text"><span class="el">or</span></p>
    <%= link_to "削除", post_path(@post), method: :delete, class:"post-destroy" %></div>
    <% else user_signed_in? && current_user.id  != @post.user_id %>
<% end %>
<% end %>
    </div>
</div>
<div class="comment-form">
    <% if user_signed_in? %>
      <%= form_with(model: [@post, @comment], local: true) do |form| %>
       <div class="com-space"> <%= form.text_area :comment_text, placeholder: "コメントする", class: "com-insert", rows: "2" %><div>
       <div class="com-contents">
        <%= form.submit "コメントする", class:"reg-btn"%>
        </div>
      <% end %>

    <% end %>
     <div class="comments">

      <% @comments.each do |comment| %>
        <p class="comment">
         <p class="user-info"> <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：
         </strong></p> <p class="comment-text"> <%= comment.comment_text %></p>
        </p>
      <% end %>
    </div>
  </div>
  </div>
  </div>
<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
<div class="footer-nav">
     <div class="footer-content"> <h3 class='footer-content-head'>HACHUHAを見る</h3>
        <ul>
        <li><%= link_to 'ポスト一覧', posts_path, class: "footer-link" %></li>
        <li><%= link_to 'ペット一覧', root_path, class: "footer-link" %></li>
      </ul>
      </div>
<div class="footer-content">
      <h2 class='footer-content-head'>HACHUHAについて</h2>
      <ul>
        <li><%= link_to 'HACHUHAガイド', "#", class: "footer-link" %></li>
      </ul>
      </div>
</div>
  <p class="copyright">© HACHUHA</p>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>

<div class="heading">
<%=link_to 'HACHUHA', root_path, id:"logo" %>
<h2 class="slogan">ペットと出会えるところ</h2>

</div>
   
   <div class="navbar">
    <ul class='nav-lists'><div> 
    <%=  link_to 'ポスト', posts_path, class: "footer-link" %></div>
      <% if user_signed_in? %>
      
      <li class="header-text"><%= link_to current_user.nickname, "/users/#{current_user.id}", class: "link"  %>さん、こんにちは！</li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "link" %></li> 
      <li><%= link_to "ペットを登録する", new_pet_path, class: "link" %>
       <li><%= link_to "ポストを投稿する", new_post_path, class: "link" %>

      <% else %>
      <li> <%= link_to 'ログイン', new_user_session_path, method: :get, class: "link" %></li>
      <li class="link"> <%= link_to '新規登録', new_user_registration_path, class: "link" %></li>
      <% end %>
    </ul></div>

</header>

app/views/users/show.html.erb
<%= render "shared/header" %>

 <div class='pet-contents'>
    <div class="subtitle" >
     <%= @nickname %>さんのペット
    </div>
    
    <ul class='pet-lists'>
      <% @pets.each do |pet| %>
      <li class='list'>
        <%= link_to pet_path(pet.id) do %>
        <div class='pet-img-content'>
          <%= image_tag pet.image, class: "pet-img"%>
        </div>
        <div class='pet-info'>
          <h3 class='pet-name'>
            <%= pet.name %>
          </h3>
        </div>
        <% end %>
      </li>
      <% end %>
    </ul>

 <% if @pets.blank? then %>
      ...まだペットを飼っていません...
   <% end %>   
</div>

<div class="contents row">
  <% @posts.each do |post| %>
    <div class="content_post" > 
   
    <span class="post-title">
        <%= post.post_title %>
           
      </span> <br>     by <a class= "user-pet" href="/users/<%= post.user.id %>"><%= post.user.nickname %>    </a>
      <p class="post-texts"><%= post.post_text %></p>
           <%= link_to "詳細", post_path(post.id) %>
    </div> 
    
  <% end %>
</div>


<%= render "shared/footer" %>